sudo: required
dist: trusty
before_install:
    - sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended latexmk texlive-lang-german texlive-doc-de texlive-math-extra latex-xcolor pgf

script:
    - mkdir output
    - latexmk -pdf Blatt01/main.tex
    - mv main.pdf output/Blatt01.pdf
    - latexmk -pdf Blatt02/main.tex
    - mv main.pdf output/Blatt02.pdf
    - latexmk -pdf Blatt03/main.tex
    - mv main.pdf output/Blatt03.pdf
    - latexmk -pdf Blatt04/main.tex
    - mv main.pdf output/Blatt04.pdf
    - latexmk -pdf Blatt05/main.tex
    - mv main.pdf output/Blatt05.pdf
    - latexmk -pdf Blatt06/main.tex
    - mv main.pdf output/Blatt06.pdf
    - latexmk -pdf Blatt07/main.tex
    - mv main.pdf output/Blatt07.pdf
    - latexmk -pdf Blatt08/main.tex
    - mv main.pdf output/Blatt08.pdf

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
    keep-history: true
    local-dir: output
    on:
        branch: master
